Adds PickerBufferTag
srstevenson/vim-picker pull request #7
Opened 2017-04-05 17:09 UTC by lwakefield

`:PickerTag` is a little slow against large tag files. `:PickerBufferTag` will run `ctags` against the current buffer then passes it along.

My vimscript is far from good, so let me know if I have made any dumb mistakes!

2017-04-09 12:08 UTC, srstevenson requested changes

2017-04-09 12:08 UTC, srstevenson commented on autoload/picker.vim
> +  return 'ctags -f - ' . a:filename . ' | grep -v "^!_TAG_" | cut -f 1 | sort -u'
The metadata lines containing `!_TAG` aren't included when `ctags` is called with `-f -` (testing with Exuberant Ctags 5.8), so the call to `grep` can be removed.

2017-04-09 12:08 UTC, srstevenson commented on README.md
> +* `:PickerBufferTag`: Pick a tag to jump to in the current buffer.
What do you think about changing this to "Pick a tag from the current buffer to jump to"? I think that would give a clearer indication of what the command does.

2017-04-09 12:08 UTC, srstevenson commented on README.md
> +nmap <unique> <leader>pb] <Plug>PickerBufferTag
Whilst testing this I found the longer mapping for `PickerBufferTag` a bit cumbersome. The `ctags` documentation uses the term "object" to refer to the symbols it indexes, so how about using `<leader>po`?

2017-04-09 12:13 UTC, srstevenson commented
@lwakefield: Thanks for contributing! I've tested this a bit over the past couple of days and quickly found it a useful addition. I've made some minor comments inline; in addition please can you include the new command in `doc/picker.txt`?

2017-04-10 12:42 UTC, lwakefield commented
Thanks for the feedback @srstevenson! This was a fairly quick and dirty hack together, so I'll make those changes over the next few days!

2017-04-10 12:43 UTC, lwakefield commented on README.md
> +nmap <unique> <leader>pb] <Plug>PickerBufferTag
That is perfect! I use a different mapping myself, so I just smooshed `pb` and `p]` together.

2017-04-20 20:12 UTC, srstevenson commented
@lwakefield: I had some spare time today, so implemented the changes and merged them as b283e04a8eea506fc2fae7f0b561d3faf25e8ec3 (you maintain authorship of the commit). Thanks!

2017-04-20 20:12 UTC, closed without merging